
System Requirements
===================

* JDK 1.6 or greater (http://java.sun.com/)
* Ant 1.7 or greater (http://ant.apache.org/)
* JUnit 3 (http://www.junit.org/)


Project Set-Up
==============

* Ensure that JUnit is on your Ant classpath
  (set the CLASSPATH environment variable accordingly):

  http://ant.apache.org/manual/OptionalTasks/junit.html

* Ensure that the LiveConnect APIs are on your classpath
  (set the CLASSPATH environment variable accordingly):

  Windows and Linux:
  http://java.sun.com/javase/6/webnotes/6u10/plugin2/liveconnect/#COMPILING

  Mac OSX:
  http://developer.apple.com/qa/qa2004/qa1364.html

* Ensure that the JAVA_HOME environment variable is set correctly
  to point to a Java 6 installation.

* Ensure that the JNLP APIs are on your classpath; follow the same process as
  above, substituting javaws.jar for plugin.jar.


Building Pivot
==============

* To compile all Pivot source files into binary class files:

  $ ant

* To generate Javadoc

  $ ant doc

* To generate the Pivot source distribution

  $ ant dist

* To generate the Pivot binary distribution

  $ ant install

NOTE The checksums for binaries generated by running the dist and install tasks
may not match the original checksums from the distribution. This is normal;
each JAR is timestamped, yielding a slightly different binary and producing a
different checksum.
