
System Requirements
===================

* Java SE JDK 5 or greater (http://java.sun.com/)
* Ant 1.7 or greater (http://ant.apache.org/)


Building Pivot
==============

* To compile all Pivot source files into binary class files:

  $ ant

* To generate Javadoc

  $ ant doc

* To generate the Pivot source distribution

  $ ant dist

* To generate the Pivot binary distribution

  $ ant install

NOTE The checksums for binaries generated by running the install task may not 
match the original checksums from the distribution. This is normal - each JAR 
is timestamped, yielding a slightly different binary and producing a different 
checksum.
